### PR TITLE
Temporarily limit setuptools version

### PR DESCRIPTION
**Pull request by decentral1se**
See https://github.com/ansible/molecule/issues/2350.

In the absence of any answers right now, let's keep the ball rolling with this temporary  fix.

### CODE REVIEW

**Comment by decentral1se** [comment]
Fix for failing CI is @ https://github.com/ansible/molecule/issues/2349#issuecomment-538970935.

**Comment by decentral1se** [comment]
Thanks @ekultails (and nice to see you around here again)!

I would love to see this bug reported but I don't have the energy to track it now.

I'll go ahead and merge this and get a green build on https://github.com/ansible/molecule/pull/2354.

**Comment by ekultails** [comment]
Glad to be back! @decentral1se I guess we'll just keep an eye on it and revisit it later. Thanks again for the patch!

**Comment by ssbarnea** [comment]
I am inclined to believe is linked to https://github.com/pypa/setuptools/issues/1869 maybe is time to obliterate the entire setup.py file, even if this risks of breaking install from source on old python versions. As long we assure we keep installation from wheel working it should be ok.

**Pull request merged**
