### PR TITLE
Documentation fix

### PR DESCRIPTION
**Pull request by robertdebock**
#### PR Type
- Docs Pull Request

The title describes "Create" but the code showed `state: destroy`.

### CODE REVIEW

**Comment by decentral1se** [comment]
Nice one! You'll need to pass the `--signoff` flag again on your commit :sweat_smile:

**Comment by robertdebock** [comment]
I guess I made a mistake somewhere, I can't get the DCO test to pass, although I've signed off locally and pushed it. Any suggestions?

**Comment by decentral1se** [comment]
Ah, you have 3 commits now and one of them is not signed. If you run a `git rebase -i HEAD~4` then you can mark those extra commits with `squash` and then mark the original commit with `edit` and then interatively add the `--signoff` marker :) Git!

**Comment by robertdebock** [comment]
> Ah, you have 3 commits now and one of them is not signed. If you run a `git rebase -i HEAD~4` then you can mark those extra commits with `squash` and then mark the original commit with `edit` and then interatively add the `--signoff` marker :) Git!
> 
> EDIT: `git reset HEAD~3` is also an option - then just make a new single commit ...

Got it, bit of messing around. Thanks!

**Comment by decentral1se** [comment]
:rocket:

**Pull request merged**
