### PR TITLE
[WIP] DNM: Demo zuul integration

### PR DESCRIPTION
**Pull request by pabelanger**
This is an example PR for zuul integration

#### PR Type

- Testing Pull Request
- Feature Pull Request

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now c53023e74bf1dd17e603995b53a3166a77f80bd0

**Comment by decentral1se** [comment]
Hey thanks @pabelanger! I'm not sure what to make of this? Could you explain further what it could mean to migrate to using Zuul. I'm really quite interested in this possibility. JFYI, we've put a lot of effort into making Travis CI work so I doubt we'll be moving off any time too soon (at least, I hope).

**Comment by pabelanger** [comment]
Sure, happy to dive into it, basically https://github.com/ansible-network/sandbox/pull/27 is demoing how you could run ansible/molecule tests from zuul. This was a friday afternoon project to help give extra information around the recent travisCI PR about future of testing.

How best do you want to get into the weeds? we could do a meeting on IRC or maybe bluejeans if people are interested in that.

You can see the results of testing, and even iterate using the PR above from ansible-network/sandbox

**Comment by decentral1se** [comment]
Thanks @pabelanger! Can you make the next WG meeting (see https://github.com/ansible/community/wiki/Molecule for timing). We could have a discussion about this. I have no idea is all this is feasible but I'm certainly interested to discuss it! @ssbarnea is also motivated to discuss.

**Comment by pabelanger** [comment]
Yes! Happy to attend.

**Comment by decentral1se** [comment]
OK, gonna close this off for now since we're tracking the movement towards Zuul over at https://github.com/ansible/molecule/issues/1770. 

Thanks for pushing this along @pabelanger!

**Pull request closed without merging**
