### PR TITLE
Added buildargs to docker_image in create.yml

### PR DESCRIPTION
**Pull request by Shaps**
Added support for image build arguments and added the reference in `docker.py`. 

#### PR Type

- Feature Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
Hey @Shaps could you please add a testcase for that?

**Comment by webknjaz** [comment]
plz rebase your changes

**Comment by Shaps** [comment]
@webknjaz Changes rebased, I have also added some tests for it, hope they are good enough?

**Comment by webknjaz** [comment]
Perfect!

**Pull request merged**
