### PR TITLE
Enable LXC and LXD functional tests under Travis CI

### PR DESCRIPTION
**Pull request by webknjaz**
#### PR Type

- Bugfix Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
@wilmardo could you please take a look at failing tests and advise what can we do about it?

**Comment by webknjaz** [comment]
It seems like we face this issue https://github.com/lxc/lxc/issues/2461

**Comment by hswong3i** [comment]
@webknjaz my repo https://github.com/alvistack/ansible-role-bootstrap are now using Molecule + LXD + Travis CI, all green for both Ubuntu/CentOS/openSUSE (https://travis-ci.org/alvistack/ansible-role-bootstrap), maybe some hints for this PR?

e.g. my LXD profile `.travis.lxcd.yml` (https://github.com/alvistack/ansible-role-bootstrap/blob/master/.travis.lxd.yml), which disable almost all security related stuff, because I am going to test it with Kubernetes and Ceph:
```
profiles:
  - name: default
    config:
      boot.autostart: "true"
      security.nesting: "true"
      security.privileged: "true"
      linux.kernel_modules: ip_tables,ip6_tables,netlink_diag,nf_nat,overlay
      raw.lxc: |
        lxc.apparmor.profile = unconfined
        lxc.cap.drop =
        lxc.cgroup.devices.allow = a
        lxc.mount.auto = proc:rw sys:rw cgroup:rw
```

For `.travis.yml` LXD and Ansible and Molecule are initialized as below (https://github.com/alvistack/ansible-role-bootstrap/blob/master/.travis.yml):
```
before_install:
  - sudo apt-get -y purge lxc-* lxd-* && sudo apt-get -y autoremove
  - sudo snap install lxd && sudo lxd init --preseed < .travis.lxd.yml
  - sudo apt-get -y purge python-openssl && sudo apt-get -y autoremove
  - sudo -H pip install --upgrade --requirement requirements.txt
```

Then a simple wrapper script for `molecule test`, so always generate a unique instance ID for each test (https://github.com/alvistack/ansible-role-bootstrap/blob/master/scripts/run-tests.sh):
```
set -o xtrace

cd "$(cd "$(dirname "$0")"; pwd -P)/../"

export ANSIBLE_FORCE_COLOR=true
export ANSIBLE_LOG_PATH="$PWD/ansible.log"
export ANSIBLE_ROLES_PATH="$HOME/.ansible/roles"

export LXC_IMAGE=${LXC_IMAGE:-"ubuntu/bionic/amd64"}
export LXC_ID=${LXC_ID:-"$(cat /dev/urandom | tr -dc a-z | head -c1)$(cat /dev/urandom | tr -dc a-z0-9 | head -c11)"}

molecule test $@
```

Finally, the `molecule/default/molecule.yml` before relatively simple (https://github.com/alvistack/ansible-role-bootstrap/blob/master/molecule/default/molecule.yml):
```
scenario:
  name: default
driver:
  name: lxd
platforms:
  - name: ${LXC_ID}-1
    url: unix:/var/snap/lxd/common/lxd/unix.socket
    source:
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: ${LXC_IMAGE}
lint:
  name: yamllint
dependency:
  name: galaxy
  options:
    role-file: ansible-role-requirements.yml
    roles-path: ${ANSIBLE_ROLES_PATH}
    ignore-errors: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${ANSIBLE_ROLES_PATH}
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
name: flake8
```

Hopefully this could give you some idea ;-)

**Comment by webknjaz** [comment]
@hswong3i thanks for the ideas! Currently, I don't have time to dig into it though. So if you decide to help, feel free to pick up this branch :)

**Pull request closed without merging**
