### PR TITLE
Move test folder to project root

### PR DESCRIPTION
**Pull request by cristianonicolai**
Moving the test folder into the project's root folder to unify developer experience when onboarding to the project. Other projects such as ansible-lint, pytest-ansible ansible-navigator already follow such structure.

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
Please add an explanation/reason in PR description, or at least a link to issues or discussion.

**Comment by cristianonicolai** [comment]
@ssbarnea can this be merged now?

**Comment by ssbarnea** [comment]
@cristianonicolai please rebase...

**Comment by cristianonicolai** [comment]
@ssbarnea done :)

**Comment by ssbarnea** [comment]
Double check with molecule-plugins to see if we have any import from molecule.test, if not, feel free to merge it.

**Review by ssbarnea — APPROVED** [review]

**Review by ajinkyau — APPROVED** [review]

**Review by Qalthos — DISMISSED** [review]
https://github.com/search?q=repo%3Aansible-community%2Fmolecule-plugins%20molecule.test&type=code

It looks like plugins is looking for conftest and b_functional.conftest to be under molecule/test.

**Comment by cristianonicolai** [comment]
@ssbarnea @Qalthos there is actually only one missing method that we need to add on molecule-plugins to remove the dependency entirely, please take a look on https://github.com/ansible-community/molecule-plugins/pull/206

**Review by cidrblock — APPROVED** [review]

**Pull request merged**
