### PR TITLE
WIP: Make OS-provided env vars override defaults

### LINKED ISSUE #1673: `MOLECULE_DEBUG` env var is not honoured
# Issue Type

- Feature request

# Desired Behavior

Like Ansible, molecule should load environment variable declared with `MOLECULE_` prefix and and use them as default values for command line arguments.

At this moment to enable debug more, user needs to add `--debug` after molecule and before the commands. This may prove quite inconvenient as the CLI call could be in a file or even other ci repository.

By regonnizing MOLECULE_DEBUG=1 it would be much easier to trigger the debug mode without having to alter the source code and the entire build chain.

Hint: Ansible has quite a nice implementaiton regarding parsing environment variables and translating them directly into default values, avoiding the need to implement this feature for each command line option.

### PR DESCRIPTION
**Pull request by webknjaz**
Fixes #1673

#### PR Type

- Bugfix Pull Request

### CODE REVIEW

**Comment by webknjaz** [comment]
Somebody plz test this :)

**Comment by decentral1se** [comment]
Oh yes, great to try and get this fixed.

I've manually tested it and didn't see `--debug` functionality occur ...

```
(.venv) ➜  testrolelatest (bugfix/allow-real-env-vars-take-precedence) ✗ export MOLECULE_DEBUG=True
(.venv) ➜  testrolelatest (bugfix/allow-real-env-vars-take-precedence) ✗ molecule create                     
--> Validating schema /home/decentral1se/ansible/molecule/testrolelatest/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── create
    └── prepare

--> Scenario: 'default'
--> Action: 'create'

    PLAY [Create] ******************************************************************

    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item=None) 

    TASK [Create Dockerfiles from image names] *************************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Discover local Docker images] ********************************************
    ok: [localhost] => (item=None)
    ok: [localhost]

    TASK [Build an Ansible compatible image] ***************************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Create docker network(s)] ************************************************

    TASK [Determine the CMD directive] *********************************************
    ok: [localhost] => (item=None)
    ok: [localhost]

    TASK [Create molecule instance(s)] *********************************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    TASK [Wait for instance(s) creation to complete] *******************************
    changed: [localhost] => (item=None)
    changed: [localhost]

    PLAY RECAP *********************************************************************
    localhost                  : ok=6    changed=4    unreachable=0    failed=0


--> Scenario: 'default'
--> Action: 'prepare'
Skipping, prepare playbook not configured.
```

I dropped into the debugger to see what was what on this run:

```
(.venv) ➜  testrolelatest (bugfix/allow-real-env-vars-take-precedence) ✗ molecule create         
> /home/decentral1se/ansible/molecule/molecule/config.py(275)_reget_config()
-> env = util.merge_dicts(self.env.copy(), os.environ)
(Pdb) self.env['MOLECULE_DEBUG']
'False'
(Pdb) os.environ['MOLECULE_DEBUG']
'True'
(Pdb) env = util.merge_dicts(self.env.copy(), os.environ)
(Pdb) env = set_env_from_file(env, self.env_file)
(Pdb) env['MOLECULE_DEBUG']
'True'
(Pdb) env = self._combine(env=env)
(Pdb) env
{'dependency': {'name': 'galaxy', 'command': None, 'enabled': True, 'options': {}, 'env': {}}, 'driver': {'name': 'docker', 'provider': {'name': None}, 'options': {'managed': True}, 'ssh_connection_options': [], 'safe_files': []}, 'lint': {'name': 'yamllint', 'enabled': True, 'options': {}, 'env': {}}, 'platforms': [{'name': 'instance', 'image': 'centos:7'}], 'provisioner': {'name': 'ansible', 'config_options': {}, 'connection_options': {}, 'options': {}, 'env': {}, 'inventory': {'hosts': {}, 'host_vars': {}, 'group_vars': {}, 'links': {}}, 'children': {}, 'playbooks': {'cleanup': 'cleanup.yml', 'create': 'create.yml', 'converge': 'playbook.yml', 'destroy': 'destroy.yml', 'prepare': 'prepare.yml', 'side_effect': 'side_effect.yml', 'verify': 'verify.yml'}, 'lint': {'name': 'ansible-lint', 'enabled': True, 'options': {}, 'env': {}}}, 'scenario': {'name': 'default', 'check_sequence': ['cleanup', 'destroy', 'dependency', 'create', 'prepare', 'converge', 'check', 'cleanup', 'destroy'], 'cleanup_sequence': ['cleanup'], 'converge_sequence': ['dependency', 'create', 'prepare', 'converge'], 'create_sequence': ['create', 'prepare'], 'destroy_sequence': ['cleanup', 'destroy'], 'test_sequence': ['lint', 'cleanup', 'destroy', 'dependency', 'syntax', 'create', 'prepare', 'converge', 'idempotence', 'side_effect', 'verify', 'cleanup', 'destroy']}, 'verifier': {'name': 'testinfra', 'enabled': True, 'directory': 'tests', 'options': {}, 'env': {}, 'additional_files_or_dirs': [], 'lint': {'name': 'flake8', 'enabled': True, 'options': {}, 'env': {}}}}
```

It's confusing that it returns the full configuration ....

It seems there is a bug further in `self._combine`?

**Comment by webknjaz** [comment]
Yeah, maybe. I didn't check it that deeply. So multiple bugs?

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/issues/1673 has been resolved by https://github.com/ansible/molecule/pull/1802 :+1:

**Comment by webknjaz** [comment]
@decentral1se does this mean that the current PR is irrelevant?

**Comment by decentral1se** [comment]
> @decentral1se does this mean that the current PR is irrelevant?

Maybe? It fixes another bug that isn't #1673?

**Comment by ssbarnea** [comment]
@webknjaz Base on the description I do not find it irrelevant. I would just wait for it to pass CI and have the "WIP" removed and I will review it. I like the idea of having a generic way to loading environment variables which would override the config ones, just like ansible.

**Comment by webknjaz** [comment]
@ssbarnea isn't that what your PR's done? I didn't inspect it closely, though.

**Comment by webknjaz** [comment]
I don't have time to work on this currently but feel free to post any thoughts or pick it up anyway :)

**Comment by decentral1se** [comment]
> have the "WIP" removed and I will review it.

It's like a 6 character change ;)

>  I like the idea of having a generic way to loading environment variables which would override the config ones, just like ansible.

Is this not already possible?

I would probably just close this off since the bug it is targetting has already been fixed.

**Pull request closed without merging**
