### PR TITLE
Documentation Update - Added a guide for using AWS EC2 Driver for molecule

### PR DESCRIPTION
**Pull request by setswei**
As mentioned in the issue ansible-community/molecule-plugins#20. I have written a guide with all supporting doco and code examples on utilising the molecule ec2 driver. I found that there were not any decent examples that worked. so I put my own together and promised to write a guide.

It is based on my boilerplate repository here -> [molecule-ec2-boilerplate](https://github.com/setswei/molecule-ec2-boilerplate)

Any questions, changes or updates you require. please let me know.

### CODE REVIEW

**Comment by setswei** [comment]
Any help to get the PR across the line would be appreciated

**Comment by matt-horwood-mayden** [comment]
Yes please, we want EC2 support please

**Comment by setswei** [comment]
I have written some doco, you can see that in the PR but tests are failing. They are discussing this PR in another conversation thread

**Comment by Qalthos** [comment]
Thanks for your submission!

In the great big split, things like this were moved to https://github.com/ansible-community/molecule-plugins. I see that's where you've come from, and they still don't have published documentation, but that is the place where this should be added. This repository is just for molecule itself, and basic use cases thereof, and this is not really in scope of that.

**Pull request closed without merging**
