### PR TITLE
📝🎨♻️ Make the PR template more detailed

### PR DESCRIPTION
**Pull request by webknjaz**
It's an improvement proposal for the current PR template. Let's make it more helpful for contributors.

#### PR Type

- Docs Pull Request
- Feature Pull Request

### CODE REVIEW

**Comment by decentral1se** [comment]
@webknjaz I do appreciate this effort but wondering if this is more helpful for contributors. The template now seems quite overwhelming to me. I am happy to defer to people who deal with such community issues more closely but my preference is "short and sweet". If we're not getting what we want out of the current template, I would suggest focusing on that and adding a new line/question/fragment instead of this "big bang" approach. This is my two cents ...

**Comment by webknjaz** [comment]
@decentral1se this is based on a few other projects I maintain. The main part I wanted to bring in is the check-list which would give contributors pointers right in their PRs... In my experience, it's quite helpful.

So yes, the number of questions might be overwhelming. I can agree with dropping some of the sections but I'd really want to see a check-list as a guidance for people who come here. Checkboxes make it possible to interactively fill in the gaps. Links to the best practices of working with Git should also be useful.
As for change note part of changelog, I thought it might be a good time to start getting used to submitting those. Even before we get changelog automation, release person would be able to reuse those manually, which should be helpful as well + it's a training for the future automation as well.

Oh, and let me add the rendered version below, so I'd be easier to reason about it...

-----------



❓ **What kind of change does this PR introduce?**
- [ ] 🐞 Bugfix Pull Request
- [ ] 🐣 Feature Pull Request
- [ ] 📋 Docs Pull Request
- [ ] 📋 Tests/coverage improvement Pull Request
- [ ] 📋 Refactoring Pull Request
- [ ] 💥 Other Pull Request

💡 **What do these changes do?**



👥 **Are there changes in behavior for the user?**



📋 **What is the related issue number (starting with `#`)**

#

❓ **What is the current behavior?** (You can also link to an open issue here)



❓ **What is the new behavior (if this is a feature change)?**



📋 **Other information**:



📋 **Contribution checklist**:
_(If you are contributing for the first time or provide a trivial fix don't worry too much about the checklist ‒ we will help you get started.
also see [CONTRIBUTING.rst](/CONTRIBUTING.rst) for details)_
- [ ] I think the code is well written
- [ ] I wrote descriptive pull request text
- [ ] I added a relevant [issue keyword][3]
      in message body
- [ ] I wrote [good commit messages][1]
- [ ] I have [squashed related commits together][2] after the changes have been approved
- [ ] Unit tests for the changes exist
- [ ] Integration tests for the changes exist (if applicable)
- [ ] I used the same coding conventions as the rest of the project
- [ ] The new code doesn't generate linter offenses
- [ ] Documentation reflects the changes
- [ ] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences
- [ ] I added a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>.rst` (for example, `588.bugfix.rst`)
  * if you don't have an `issue_id` change it to the PR id after creating it
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * "sign" fragment with "by @<your username>"
  * Make sure to use full sentences with correct case and punctuation, for example:
    ```
    "Fix issue with non-ascii contents in doctest text files ‒ by :user:`superuser`."
    ```


[1]: https://chris.beams.io/posts/git-commit/
[2]: https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit
[3]: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by MarkusTeufelberger** [comment]
I'm not too fond of these emojis all over the place, otherwise it is a good idea to have people think a bit about their contributions.

The thing that's keeping me personally from contributing to this project any more is the requirement for adding `--signoff` to commits, these are just noise and don't imply anything legally other than making it more annoying to contribute here. Ironically this isn't even mentioned in the template as a requirement for PRs.

**Comment by decentral1se** [comment]
> The thing that's keeping me personally from contributing to this project any more is the requirement for adding --signoff to commits,

/cc @ssbarnea. @MarkusTeufelberger, I will try to raise this at the following WG but might forget (as I don't really mind this requirement at all). If you have time, please join to push for removing the DCO (see https://github.com/ansible/community/wiki/Molecule for times).

**Comment by webknjaz** [comment]
> just noise and don't imply anything legally

Not true. Signing DCO certifies that you possess the right to submit the code. Personally, I'd **also** require the commit to be GPG-signed.

**Comment by MarkusTeufelberger** [comment]
Yes, signing the DCO. There's an author field in every git commit though, adding `--signoff` doesn't add anything of value, especially on your own commits.

GPG signing commits instead of adding a signoff string would be a much better alternative.

**Comment by webknjaz** [comment]
@MarkusTeufelberger author field is just a part of metadata and is usually set as per configuration of your local Git. Sign-off is more of a conscious thing. Author field is a commit usually means that you created the commit, not that you created the code. (Yes, I know that committer is a separate field, but that's a technical detail).
Same thing for GPG. It only confirms that it was signed by your key, it doesn't certify that you have a right to submit code somewhere.

**Comment by MarkusTeufelberger** [comment]
I can add the sign-off text also randomly, it doesn't certify anything.

**Comment by webknjaz** [comment]
@MarkusTeufelberger legally it has a meaning

**Comment by MarkusTeufelberger** [comment]
Only in the context of the preamble of https://github.com/ansible/molecule/blob/master/DCO_1_1.md

One could easily change "All contributors must use git commit --signoff for any commit to be merged, and agree that usage of --signoff constitutes agreement with the terms of DCO 1.1[...]" to "All contributors must agree that merging code to this repository constitutes agreement with the terms of DCO 1.1".

Legally under GDPR I also have the right to have my personal data (which includes my mail address and name) being removed from this project permanently in the future...

**Comment by gundalow** [comment]
All, 
Can we please avoid discussing DCO sign off in this PR, as that's off topic.

This PR is about improving the template.

**Comment by webknjaz** [comment]
@gundalow bump

**Pull request closed without merging**
