### PR TITLE
add ansible_args to the ansible provisioner

### PR DESCRIPTION
**Pull request by singuliere**
provisioner:
          name: ansible
          ansible_args:
            - --inventory=mygroups.yml
            - --limit=host1,host2

Fixes https://github.com/ansible/molecule/issues/1650

Signed-off-by: singuliere <singuliere@autistici.org>

#### PR Type

- Feature Pull Request

### CODE REVIEW

**Comment by singuliere** [comment]
A [test failed](https://travis-ci.com/ansible/molecule/jobs/168502059) with:

```
PluginValidationError: Plugin 'pytest_cov' could not be loaded:
```

Since this pull request does not modify anything in the tox configuration or the requirements, I'll try to re-run and verify it is a transient error.

**Comment by singuliere** [comment]
A [single test failed](https://api.travis-ci.com/v3/job/168850882/log.txt) because of what seems to be an unrelated error:

```
Coverage.py warning: Couldn't read data from '/home/travis/build/ansible/molecule/test/scenarios/driver/docker/molecule/default/.coverage.travis-job-c2d02508-1611-43b6-a4ed-aed6feb2845c.1175.373812': ValueError: Unterminated string starting at: line 1 column 4010 (char 4009)
```

re-pushing to verify this is a transient error.

**Comment by singuliere** [comment]
There is [one job failure](https://travis-ci.com/ansible/molecule/jobs/168881924) that ends with:

```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

**Comment by lwm** [comment]
Thanks for struggling on with this CI @singuliere!

**Comment by singuliere** [comment]
Using a combination of Travis CI runs to workaround the jobs that timeout:

* https://travis-ci.com/ansible/molecule/builds/96645264 all tests pass except 19
* https://travis-ci.com/ansible/molecule/builds/96714916 **in progress**

**Comment by singuliere** [comment]
rebased and repushed now that the pytest-cov dependency problem is fixed

**Comment by singuliere** [comment]
rebased and repushed now that the pytest-cov dependency problem is fixed

**Comment by lwm** [comment]
LGTM

**Comment by singuliere** [comment]
rebased and re-pushed

**Comment by lwm** [comment]
Added to agenda in https://github.com/ansible/community/issues/427. Please join if you have time!

**Comment by singuliere** [comment]
@lwm I will, thanks for the reminder and the grooming :sparkles:

**Comment by singuliere** [comment]
fixed a problem that made yapf unhappy & repushed. Fingers crossed :-)

**Comment by singuliere** [comment]
could someone please add the **enhancement** label to this PR? Just cosmetic, no worries if noone does it ;-)

**Comment by singuliere** [comment]
I won't have time to take care of this pull request in the immediate future. If someone else is interested, feel free to cherry-pick into another pull request.

**Comment by lwm** [comment]
Let's see if we can't get this merged again then :+1:

**Pull request merged**
