### PR TITLE
Add an initial GitHub code owners config

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
When was this decided who owns that code and by whom?!

**Comment by webknjaz** [comment]
@MarkusTeufelberger it's just me. This file helps GitHub to add me as a reviewer. Just that. Unfortunately, in only works with org members :(

**Comment by webknjaz** [comment]
If somebody else wants to be added there — feel free. But it's just a config for GitHub itself for convenience.

**Comment by MarkusTeufelberger** [comment]
Ok, thanks for the clarification.

**Comment by webknjaz** [comment]
Ref: https://help.github.com/en/articles/about-code-owners

**Comment by MarkusTeufelberger** [comment]
Ok, so basically an auto-"ping" if certain files are modified in a PR.

**Comment by webknjaz** [comment]
Yes. Kinda. In ansible/ansible we have ansibot which does manual pings based on a custom config. But it's very tightly coupled with that repo and we cannot reuse that. Yet I hope to be able to distill some stateless parts of bot logic into a reusable GitHub App sometime.

**Comment by decentral1se** [comment]
"CODEOWNERS" is a problematic naming issue :)

**Comment by webknjaz** [comment]
@decentral1se yes, but it's a defacto standard. I've heard it a lot for years. "[team] code ownership" and related stuff is often mentioned along with DevOps/Agile methodologies explanations.

I can see how that can be problematic yet I don't know how to improve it...

**Comment by decentral1se** [comment]
How about "POINTOFCONTACT", "WHOKNOWSMORE", "CARETAKERS", "VERYPASSIONATEABOUTTHISFILE" ...

**Comment by webknjaz** [comment]
Yes, but I was talking about GitHub understanding only this file name.

**Comment by webknjaz** [comment]
We should also think about adding other files like https://help.github.com/en/articles/adding-support-resources-to-your-project indicating common policies/principles of getting help...

**Pull request merged**
