### PR TITLE
Fixed deprecation warning for pytest.config in test/conftest.py.

### PR DESCRIPTION
**Pull request by atombrella**

### CODE REVIEW

**Comment by decentral1se** [comment]
CI is complaining though ...

https://travis-ci.com/ansible/molecule/jobs/219081211

Don't merge yet anyone :)

**Comment by ssbarnea** [comment]
@atombrella Can you look into it? I would be very happy to see this fixed as it really annoying to keep seeing those warnings.

**Comment by atombrella** [comment]
@ssbarnea Yes, I'll give it a shot. Is there a bounty? :)

**Comment by ssbarnea** [comment]
>@ssbarnea Yes, I'll give it a shot.

@atombrella Any update on this? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atombrella** [comment]
@ssbarnea I had a look, but I'm not sure how much that needs to be changed. The `pytest_collection_modifyitems` has some examples at https://docs.pytest.org/en/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option on how to skip tests. I'm not sure how much that needs to be changed, e.g., if specific markers need to be configure, or if a relatively small change can do the trick.

**Comment by atombrella** [comment]
@ssbarnea I have no idea how to fix this. So I'm closing this PR.

**Pull request closed without merging**
