### PR TITLE
Pull docker containers at launch as well as build.

### PR DESCRIPTION
**Pull request by skyscooby**
Add pull to docker_container module
Closes: #2149

### CODE REVIEW

**Comment by skyscooby** [comment]
DCO added. In terms of tests I added the parameter into the create.yml used by the tests however I'm not sure there is any specific scenario testing around the pull feature. I'll leave that to those intimate with the test suite to decide.

**Comment by wilmardo** [comment]
@skyscooby  Thanks for the PR! To be awesome this needs an update in the `molecule/model/schema_v2.py` and then tests added in `test/unit/model/v2/test_platforms_section.py`

See https://github.com/ansible/molecule/pull/2192 for an example (not a real clean example, if you just look at sysctl it should be clear)

**Comment by skyscooby** [comment]
Thanks @wilmardo, as near as I can tell these two files already have the pull parameter defined. This is not a new parameter but simply attaching the pull request to the launch of the docker container rather than using it only on the build step.

**Comment by wilmardo** [comment]
Ah cool missed that, thanks for checking!

**Pull request merged**
