### PR TITLE
Allow molecule to list scenarios present under molecule directory within a collection

### PR DESCRIPTION
**Pull request by ajinkyau**
Related: #3987

### CODE REVIEW

**Review by ssbarnea — CHANGES_REQUESTED** [review]
The fact this this passed packaging worries me because we added a new dependency which we failed to declare. That job should have failed. We better find a way to make it fail if we do this to avoid adding hidden deps. I am trying to figure-out how to do this properly...

**Comment by cidrblock** [comment]
yeah, looks like it got pulled in from ansible-lint https://github.com/ansible/molecule/actions/runs/5785724537/job/15678953688#step:9:369

I think we should be able to do this without wcmatch though......or at least wait until we get a issue that can';t be resolved without it.

**Comment by ssbarnea** [comment]
> 

I told @ajinkyau to use wcmatch, that is not an issue. The issue is that we did not declare it as a direct dependency. 

Second issue is why it got installed as I doubt we want to install ansible-lint in normal testing environments. I am still looking for a tool that can help us detect missing direct dependencies but i did not find one that works with modern packaging.

**Comment by cidrblock** [comment]
ansible-lint is a dep for test........could we remove that?

I'll look into wcamtch, I'm not familiar enough with it to grok what it does above the std lib

**Review by cidrblock — APPROVED** [review]

**Pull request merged**
