### PR TITLE
Bump ansible-lint to 3.5.1

### LINKED ISSUE #1525: ansible-lint version needs bumped to 3.5.1
# Issue Type
- Feature request

In the currently referenced version of `ansible-lint`, it will silently not parse tasks files that are included via `import_tasks`/`import_roles`. This bug has since been fixed -- when I manually specify `ansible-lint==3.5.1` in my requirements.txt, the behavior is resolved. It would be nice to get rid of that version pinning in my requirements.txt, and I'm sure users of molecule would appreciate their linter not silently ignoring some of their files :)

I haven't run into any incompatibilities so far.

Here's the PR with the fix https://github.com/willthames/ansible-lint/pull/365

# Molecule and Ansible details

```
ansible --version
```
2.6.1

```
molecule --version
```
2.19.0

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- pip

### PR DESCRIPTION
**Pull request by wilmardo**
Fixes #1525

### CODE REVIEW

**Comment by gundalow** [comment]
Setting as v2.20 milestone (next release)

**Comment by webknjaz** [comment]
@gundalow automatic periodic version bump PRs can be done by pyup (demo: https://github.com/aio-libs/multidict/pull/300) or dependabot (demo: https://github.com/github/opensource.guide/pull/742)

**Comment by ssbarnea** [comment]
This clearly needs to go in as it fixed a serious bug. I am not sure if pinning of ansible-lint is the best idea but this would deserve a new bug and consultation.

There are pros and cons for both approaches but maybe in the future we could go for a mixed approach: having unpinned versions in requirements.txt and and adding an extra named "pinned" that has the pinned versions. So users that want extra satbility can install `molecule[pinned]` and those that are more flexible can install `molecule`. Obviously that even the non pinned version would need ranged, at least >= if not even capped ones.

The way it was proposed in the tox.ini PR looks like a good traddeoff between safety and maintenance.

**Comment by webknjaz** [comment]
Hey @ssbarnea,

Let me add a few points to the discussion.

1) Let's not confuse environment dependencies and distribution package requirements. It's encouraged to pin deps for env, but not library-like things. The reason is that it breaks user's ability to install things with conflicting deps alongside or to pin them to versions they want within their (virtual)envs, for example.
OTOH setting a lower bound is a good idea and it's fine with me. Another thing we can do is to explicitly forbid certain faulty dependency versions, like `ansible-lint>=x.y.z,!=x.y.a`.
2) I like the idea of having "pinned" extra. Nice thing is that we could do post-releases only updating that pinned dependency (I mean like `.post0`, see PEP 440)

**Comment by webknjaz** [comment]
Hey @wilmardo, please rebase this PR.

**Comment by wilmardo** [comment]
@webknjaz Done :smile:

**Comment by webknjaz** [comment]
It looks like you hit an unstable job. I've restarted it to see what happens :)

**Pull request merged**
