### PR TITLE
WIP DNM - testing zuul integration

### PR DESCRIPTION
**Pull request by pabelanger**
This PR is used to trigger builds on zuul.ansible.com for the zuul demo

#### PR Type

- Feature Pull Request

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 38c282116651519bcc008fb23289b8cf72d4ff76

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now a374c17e0ffa24bd07e9e19c8273d1d6b9730741

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now c88adbb72057d149f7fcc72bcc6c7f09e25631b5

**Comment by ssbarnea** [comment]
I am closing it because I being told that zuul integration is not ready for use. @pabelanger please ping me as soon we can resume the work on this direction.

**Comment by pabelanger** [comment]
Closing is fine, on our side, zuul.a.c is ready, but I have seen push back from people about long term support of it.  Basically a staffing problem, until that gets discussed I don't see more projects onboarding due to this.

**Pull request closed without merging**
